import sys
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from T2SIC import Ui_ot as Ui
from text_2_speechFIN import *
from ipa_chart_soundsFIN import *

class IPALabUI(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self, None)
        self.ui = Ui()
        self.uisetupUi(self)
        self.ui.p.clicked.connect(_translate("ot", "p"))
        self.ui.b.clicked.connect(_translate("ot", "b"))
        self.ui.m.clicked.connect(_translate("ot", "m"))
        self.ui.br.clicked.connect(_translate("ot", "ʙ"))
        self.ui.vh.clicked.connect(_translate("ot", "β"))
        self.ui.fh.clicked.connect(_translate("ot", "ɸ"))
        self.ui.mh.clicked.connect(_translate("ot", "ɱ"))
        self.ui.vr.clicked.connect(_translate("ot", "ⱱ"))
        self.ui.v.clicked.connect(_translate("ot", "v"))
        self.ui.f.clicked.connect(_translate("ot", "f"))
        self.ui.vi.clicked.connect(_translate("ot", "ʋ"))
        self.ui.z_.clicked.connect(_translate("ot", "ʐ"))
        self.ui.n_.clicked.connect(_translate("ot", "ɳ"))
        self.ui.d_.clicked.connect(_translate("ot", "ɖ"))
        self.ui.r_.clicked.connect(_translate("ot", "ɽ"))
        self.ui.l_.clicked.connect(_translate("ot", "ɭ"))
        self.ui.rh_.clicked.connect(_translate("ot", "ɻ"))
        self.ui.s.clicked.connect(_translate("ot", "s"))
        self.ui.lh.clicked.connect(_translate("ot", "ɬ"))
        self.ui.dh.clicked.connect(_translate("ot", "ð"))
        self.ui.th.clicked.connect(_translate("ot", "θ"))
        self.ui.t.clicked.connect(_translate("ot", "t"))
        self.ui.sh.clicked.connect(_translate("ot", "ʃ"))
        self.ui.zh_2.clicked.connect(_translate("ot", "ʒ"))
        self.ui.t_.clicked.connect(_translate("ot", "ʈ"))
        self.ui.s_.clicked.connect(_translate("ot", "ʂ"))
        self.ui.ny.clicked.connect(_translate("ot", "ɲ"))
        self.ui.ghy.clicked.connect(_translate("ot", "ʝ"))
        self.ui.c.clicked.connect(_translate("ot", "c"))
        self.ui.j.clicked.connect(_translate("ot", "j"))
        self.ui.xy.clicked.connect(_translate("ot", "ç"))
        self.ui.ly.clicked.connect(_translate("ot", "ʎ"))
        self.ui.jy.clicked.connect(_translate("ot", "ɟ"))
        self.ui.g.clicked.connect(_translate("ot", "g"))
        self.ui.k.clicked.connect(_translate("ot", "k"))
        self.ui.ng.clicked.connect(_translate("ot", "ŋ"))
        self.ui.x.clicked.connect(_translate("ot", "x"))
        self.ui.gh.clicked.connect(_translate("ot", "ɣ"))
        self.ui.lg.clicked.connect(_translate("ot", "ʟ"))
        self.ui.jg.clicked.connect(_translate("ot", "ɰ"))
        self.ui.ghq.clicked.connect(_translate("ot", "ʁ"))
        self.ui.nq.clicked.connect(_translate("ot", "ɴ"))
        self.ui.xq.clicked.connect(_translate("ot", "χ"))
        self.ui.q.clicked.connect(_translate("ot", "q"))
        self.ui.gq.clicked.connect(_translate("ot", "ɢ"))
        self.ui.rq.clicked.connect(_translate("ot", "ʀ"))
        self.ui.h.clicked.connect(_translate("ot", "h"))
        self.ui.hhh.clicked.connect(_translate("ot", "ɦ"))
        self.ui.hh.clicked.connect(_translate("ot", "ħ"))
        self.ui.ha.clicked.connect(_translate("ot", "ʕ"))
        self.ui.xa.clicked.connect(_translate("ot", "ʔ"))
        self.ui.rh.clicked.connect(_translate("ot", "ɹ"))
        self.ui.n.clicked.connect(_translate("ot", "n"))
        self.ui.zh.clicked.connect(_translate("ot", "z"))
        self.ui.r.clicked.connect(_translate("ot", "r"))
        self.ui.l.clicked.connect(_translate("ot", "l"))
        self.ui.d.clicked.connect(_translate("ot", "d"))
        self.ui.rr.clicked.connect(_translate("ot", "ɾ"))
        self.ui.lzh.clicked.connect(_translate("ot", "ɮ"))
        self.ui.label_3.clicked.connect(_translate("ot", "Consonants (Pulmonic)"))
        self.ui.label_21.clicked.connect(_translate("ot", "Consonants (Non-pulmonic)"))
        self.ui.label_22.clicked.connect(_translate("ot", "Clicks"))
        self.ui.label_23.clicked.connect(_translate("ot", "Voiced Implosives"))
        self.ui.label_24.clicked.connect(_translate("ot", "Ejectives"))
        self.ui.ac.clicked.connect(_translate("ot", "!"))
        self.ui.dc.clicked.connect(_translate("ot", "ǀ"))
        self.ui.bc.clicked.connect(_translate("ot", "ʘ"))
        self.ui.alc.clicked.connect(_translate("ot", "||"))
        self.ui.pac.clicked.connect(_translate("ot", "ǂ"))
        self.ui.gqi.clicked.connect(_translate("ot", "ʛ"))
        self.ui.gi.clicked.connect(_translate("ot", "ɠ"))
        self.ui.ji.clicked.connect(_translate("ot", "ʄ"))
        self.ui.bi.clicked.connect(_translate("ot", "ɓ"))
        self.ui.di.clicked.connect(_translate("ot", "ɗ"))
        self.ui.pe.clicked.connect(_translate("ot", "p\'"))
        self.ui.te.clicked.connect(_translate("ot", "t\'"))
        self.ui.ke.clicked.connect(_translate("ot", "k\'"))
        self.ui.se.clicked.connect(_translate("ot", "s\'"))
        self.ui.wy.clicked.connect(_translate("ot", "ɥ"))
        self.ui.wh.clicked.connect(_translate("ot", "ʍ"))
        self.ui.heg.clicked.connect(_translate("ot", "ʜ"))
        self.ui.w.clicked.connect(_translate("ot", "w"))
        self.ui.aeg.clicked.connect(_translate("ot", "ʢ"))
        self.ui.xeg.clicked.connect(_translate("ot", "ʡ"))
        self.ui.ts.clicked.connect(_translate("ot", "t͡s"))
        self.ui.zy.clicked.connect(_translate("ot", "ʑ"))
        self.ui.lll.clicked.connect(_translate("ot", "˩"))
        self.ui.kp.clicked.connect(_translate("ot", "k͡p"))
        self.ui.sy.clicked.connect(_translate("ot", "ɕ"))
        self.ui.i.clicked.connect(_translate("ot", "i"))
        self.ui.y.clicked.connect(_translate("ot", "y"))
        self.ui.il.clicked.connect(_translate("ot", "ɪ"))
        self.ui.yl.clicked.connect(_translate("ot", "ʏ"))
        self.ui.oe.clicked.connect(_translate("ot", "ø"))
        self.ui.e.clicked.connect(_translate("ot", "e"))
        self.ui.et.clicked.connect(_translate("ot", "ɛ"))
        self.ui.oet.clicked.connect(_translate("ot", "œ"))
        self.ui.oett.clicked.connect(_translate("ot", "ɶ"))
        self.ui.a.clicked.connect(_translate("ot", "a"))
        self.ui.ae.clicked.connect(_translate("ot", "æ"))
        self.ui.ih.clicked.connect(_translate("ot", "ɨ"))
        self.ui.uh.clicked.connect(_translate("ot", "ʉ"))
        self.ui.eh.clicked.connect(_translate("ot", "ɘ"))
        self.ui.oh.clicked.connect(_translate("ot", "ɵ"))
        self.ui.a_.clicked.connect(_translate("ot", "ə"))
        self.ui.eht.clicked.connect(_translate("ot", "ɜ"))
        self.ui.aw.clicked.connect(_translate("ot", "ɐ"))
        self.ui.oht.clicked.connect(_translate("ot", "ɞ"))
        self.ui.eu.clicked.connect(_translate("ot", "ɯ"))
        self.ui.u.clicked.connect(_translate("ot", "u"))
        self.ui.ul.clicked.connect(_translate("ot", "ʊ"))
        self.ui.ue.clicked.connect(_translate("ot", "ɤ"))
        self.ui.o.clicked.connect(_translate("ot", "o"))
        self.ui.aht.clicked.connect(_translate("ot", "ʌ"))
        self.ui.pushButton_110.clicked.connect(_translate("ot", "ɔ"))
        self.ui.ah.clicked.connect(_translate("ot", "ɑ"))
        self.ui.ao.clicked.connect(_translate("ot", "ɒ"))
        self.ui.pron_mode.clicked.connect(_translate("ot", "Pronunce alphabet mode"))
        self.ui.t2s_mode.clicked.connect(_translate("ot", "Text-to-speech mode"))
        self.ui.t2s_pronunce.clicked.connect(_translate("ot", "Pronunce"))

def main():
    app = QApplication(sys.argv)
    w = IPALabUI()
    w.show()
    return app.exec_()

if __name__ == "__main__":
    sys.exit(main())
