# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsMenu(object):
    def setupUi(self, OptionsMenu):
        OptionsMenu.setObjectName("OptionsMenu")
        OptionsMenu.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(OptionsMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 50, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 80, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 121, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 761, 21))
        self.label_9.setObjectName("label_9")
        self.helpText = QtWidgets.QLabel(self.centralwidget)
        self.helpText.setGeometry(QtCore.QRect(10, 290, 861, 141))
        self.helpText.setWordWrap(True)
        self.helpText.setObjectName("helpText")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 440, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.messageReport = QtWidgets.QLineEdit(self.centralwidget)
        self.messageReport.setGeometry(QtCore.QRect(10, 510, 741, 25))
        self.messageReport.setObjectName("messageReport")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 480, 761, 21))
        self.label_13.setObjectName("label_13")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(760, 503, 112, 31))
        self.sendButton.setObjectName("sendButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 220, 291, 25))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.versionNum = QtWidgets.QLabel(self.centralwidget)
        self.versionNum.setGeometry(QtCore.QRect(120, 190, 68, 19))
        self.versionNum.setObjectName("versionNum")
        self.firstName = QtWidgets.QLabel(self.centralwidget)
        self.firstName.setGeometry(QtCore.QRect(110, 50, 161, 19))
        self.firstName.setObjectName("firstName")
        self.userName = QtWidgets.QLabel(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(110, 80, 161, 19))
        self.userName.setObjectName("userName")
        self.userEmail = QtWidgets.QLabel(self.centralwidget)
        self.userEmail.setGeometry(QtCore.QRect(370, 80, 131, 19))
        self.userEmail.setObjectName("userEmail")
        self.lastName = QtWidgets.QLabel(self.centralwidget)
        self.lastName.setGeometry(QtCore.QRect(370, 50, 141, 19))
        self.lastName.setObjectName("lastName")
        self.quizRes = QtWidgets.QLabel(self.centralwidget)
        self.quizRes.setGeometry(QtCore.QRect(540, 50, 311, 71))
        self.quizRes.setWordWrap(True)
        self.quizRes.setObjectName("quizRes")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(530, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        OptionsMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OptionsMenu)
        self.statusbar.setObjectName("statusbar")
        OptionsMenu.setStatusBar(self.statusbar)

        self.retranslateUi(OptionsMenu)
        QtCore.QMetaObject.connectSlotsByName(OptionsMenu)

    def retranslateUi(self, OptionsMenu):
        _translate = QtCore.QCoreApplication.translate
        OptionsMenu.setWindowTitle(_translate("OptionsMenu", "Options Menu"))
        self.label.setText(_translate("OptionsMenu", "User Info"))
        self.label_2.setText(_translate("OptionsMenu", "Username:"))
        self.label_3.setText(_translate("OptionsMenu", "First name:"))
        self.label_4.setText(_translate("OptionsMenu", "Last name:"))
        self.label_5.setText(_translate("OptionsMenu", "E-mail:"))
        self.label_6.setText(_translate("OptionsMenu", "Version:"))
        self.label_7.setText(_translate("OptionsMenu", "Application Info"))
        self.label_8.setText(_translate("OptionsMenu", "GitHub Page:"))
        self.label_9.setText(_translate("OptionsMenu", "Developers: 58090002 Damian Satya Wibowo, 59090025 Punn Ouilapan, 59090038 Warakorn Jetlohasiri"))
        self.helpText.setText(_translate("OptionsMenu", "[Help section loaded from text file]"))
        self.label_11.setText(_translate("OptionsMenu", "How to Use Linguis"))
        self.label_12.setText(_translate("OptionsMenu", "Report Bug/Contact Developer"))
        self.label_13.setText(_translate("OptionsMenu", "Enter your message here:"))
        self.sendButton.setText(_translate("OptionsMenu", "Send"))
        self.lineEdit_2.setText(_translate("OptionsMenu", "https://github.com/squidpurin/Linguis"))
        self.versionNum.setText(_translate("OptionsMenu", "[version]"))
        self.firstName.setText(_translate("OptionsMenu", "[fn]"))
        self.userName.setText(_translate("OptionsMenu", "[un]"))
        self.userEmail.setText(_translate("OptionsMenu", "[em]"))
        self.lastName.setText(_translate("OptionsMenu", "[ln]"))
        self.quizRes.setText(_translate("OptionsMenu", "[QuizRes]"))
        self.label_14.setText(_translate("OptionsMenu", "Quiz Results"))

