# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ipachart.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ot(object):
    def setupUi(self, ot):
        ot.setObjectName("ot")
        ot.resize(900, 787)
        self.centralwidget = QtWidgets.QWidget(ot)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 68, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 91, 19))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 91, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 20, 68, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 20, 61, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(390, 10, 91, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 20, 68, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 20, 91, 19))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(680, 20, 68, 19))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(810, 20, 68, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(730, 20, 91, 19))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 68, 19))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 68, 19))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 150, 68, 19))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 120, 68, 19))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 180, 68, 19))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 210, 91, 19))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 240, 91, 19))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 270, 91, 19))
        self.label_20.setObjectName("label_20")
        self.p = QtWidgets.QPushButton(self.centralwidget)
        self.p.setGeometry(QtCore.QRect(110, 50, 31, 31))
        self.p.setObjectName("p")
        self.b = QtWidgets.QPushButton(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(140, 50, 31, 31))
        self.b.setObjectName("b")
        self.m = QtWidgets.QPushButton(self.centralwidget)
        self.m.setGeometry(QtCore.QRect(140, 80, 31, 31))
        self.m.setObjectName("m")
        self.br = QtWidgets.QPushButton(self.centralwidget)
        self.br.setGeometry(QtCore.QRect(140, 110, 31, 31))
        self.br.setObjectName("br")
        self.vh = QtWidgets.QPushButton(self.centralwidget)
        self.vh.setGeometry(QtCore.QRect(140, 170, 31, 31))
        self.vh.setObjectName("vh")
        self.fh = QtWidgets.QPushButton(self.centralwidget)
        self.fh.setGeometry(QtCore.QRect(110, 170, 31, 31))
        self.fh.setObjectName("fh")
        self.mh = QtWidgets.QPushButton(self.centralwidget)
        self.mh.setGeometry(QtCore.QRect(210, 80, 31, 31))
        self.mh.setObjectName("mh")
        self.vr = QtWidgets.QPushButton(self.centralwidget)
        self.vr.setGeometry(QtCore.QRect(210, 140, 31, 31))
        self.vr.setObjectName("vr")
        self.v = QtWidgets.QPushButton(self.centralwidget)
        self.v.setGeometry(QtCore.QRect(210, 170, 31, 31))
        self.v.setObjectName("v")
        self.f = QtWidgets.QPushButton(self.centralwidget)
        self.f.setGeometry(QtCore.QRect(180, 170, 31, 31))
        self.f.setObjectName("f")
        self.vi = QtWidgets.QPushButton(self.centralwidget)
        self.vi.setGeometry(QtCore.QRect(210, 230, 31, 31))
        self.vi.setObjectName("vi")
        self.z_ = QtWidgets.QPushButton(self.centralwidget)
        self.z_.setGeometry(QtCore.QRect(490, 170, 31, 31))
        self.z_.setObjectName("z_")
        self.n_ = QtWidgets.QPushButton(self.centralwidget)
        self.n_.setGeometry(QtCore.QRect(490, 80, 31, 31))
        self.n_.setObjectName("n_")
        self.d_ = QtWidgets.QPushButton(self.centralwidget)
        self.d_.setGeometry(QtCore.QRect(490, 50, 31, 31))
        self.d_.setObjectName("d_")
        self.r_ = QtWidgets.QPushButton(self.centralwidget)
        self.r_.setGeometry(QtCore.QRect(490, 140, 31, 31))
        self.r_.setObjectName("r_")
        self.l_ = QtWidgets.QPushButton(self.centralwidget)
        self.l_.setGeometry(QtCore.QRect(490, 260, 31, 31))
        self.l_.setObjectName("l_")
        self.rh_ = QtWidgets.QPushButton(self.centralwidget)
        self.rh_.setGeometry(QtCore.QRect(490, 230, 31, 31))
        self.rh_.setObjectName("rh_")
        self.s = QtWidgets.QPushButton(self.centralwidget)
        self.s.setGeometry(QtCore.QRect(320, 170, 31, 31))
        self.s.setObjectName("s")
        self.lh = QtWidgets.QPushButton(self.centralwidget)
        self.lh.setGeometry(QtCore.QRect(320, 200, 31, 31))
        self.lh.setObjectName("lh")
        self.dh = QtWidgets.QPushButton(self.centralwidget)
        self.dh.setGeometry(QtCore.QRect(280, 170, 31, 31))
        self.dh.setObjectName("dh")
        self.th = QtWidgets.QPushButton(self.centralwidget)
        self.th.setGeometry(QtCore.QRect(250, 170, 31, 31))
        self.th.setObjectName("th")
        self.t = QtWidgets.QPushButton(self.centralwidget)
        self.t.setGeometry(QtCore.QRect(320, 50, 31, 31))
        self.t.setObjectName("t")
        self.sh = QtWidgets.QPushButton(self.centralwidget)
        self.sh.setGeometry(QtCore.QRect(390, 170, 31, 31))
        self.sh.setObjectName("sh")
        self.zh_2 = QtWidgets.QPushButton(self.centralwidget)
        self.zh_2.setGeometry(QtCore.QRect(420, 170, 31, 31))
        self.zh_2.setObjectName("zh_2")
        self.t_ = QtWidgets.QPushButton(self.centralwidget)
        self.t_.setGeometry(QtCore.QRect(460, 50, 31, 31))
        self.t_.setObjectName("t_")
        self.s_ = QtWidgets.QPushButton(self.centralwidget)
        self.s_.setGeometry(QtCore.QRect(460, 170, 31, 31))
        self.s_.setObjectName("s_")
        self.ny = QtWidgets.QPushButton(self.centralwidget)
        self.ny.setGeometry(QtCore.QRect(560, 80, 31, 31))
        self.ny.setObjectName("ny")
        self.ghy = QtWidgets.QPushButton(self.centralwidget)
        self.ghy.setGeometry(QtCore.QRect(560, 170, 31, 31))
        self.ghy.setObjectName("ghy")
        self.c = QtWidgets.QPushButton(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(530, 50, 31, 31))
        self.c.setObjectName("c")
        self.j = QtWidgets.QPushButton(self.centralwidget)
        self.j.setGeometry(QtCore.QRect(560, 230, 31, 31))
        self.j.setObjectName("j")
        self.xy = QtWidgets.QPushButton(self.centralwidget)
        self.xy.setGeometry(QtCore.QRect(530, 170, 31, 31))
        self.xy.setObjectName("xy")
        self.ly = QtWidgets.QPushButton(self.centralwidget)
        self.ly.setGeometry(QtCore.QRect(560, 260, 31, 31))
        self.ly.setObjectName("ly")
        self.jy = QtWidgets.QPushButton(self.centralwidget)
        self.jy.setGeometry(QtCore.QRect(560, 50, 31, 31))
        self.jy.setObjectName("jy")
        self.g = QtWidgets.QPushButton(self.centralwidget)
        self.g.setGeometry(QtCore.QRect(630, 50, 31, 31))
        self.g.setObjectName("g")
        self.k = QtWidgets.QPushButton(self.centralwidget)
        self.k.setGeometry(QtCore.QRect(600, 50, 31, 31))
        self.k.setObjectName("k")
        self.ng = QtWidgets.QPushButton(self.centralwidget)
        self.ng.setGeometry(QtCore.QRect(630, 80, 31, 31))
        self.ng.setObjectName("ng")
        self.x = QtWidgets.QPushButton(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(600, 170, 31, 31))
        self.x.setObjectName("x")
        self.gh = QtWidgets.QPushButton(self.centralwidget)
        self.gh.setGeometry(QtCore.QRect(630, 170, 31, 31))
        self.gh.setObjectName("gh")
        self.lg = QtWidgets.QPushButton(self.centralwidget)
        self.lg.setGeometry(QtCore.QRect(630, 260, 31, 31))
        self.lg.setObjectName("lg")
        self.jg = QtWidgets.QPushButton(self.centralwidget)
        self.jg.setGeometry(QtCore.QRect(630, 230, 31, 31))
        self.jg.setObjectName("jg")
        self.ghq = QtWidgets.QPushButton(self.centralwidget)
        self.ghq.setGeometry(QtCore.QRect(700, 170, 31, 31))
        self.ghq.setObjectName("ghq")
        self.nq = QtWidgets.QPushButton(self.centralwidget)
        self.nq.setGeometry(QtCore.QRect(700, 80, 31, 31))
        self.nq.setObjectName("nq")
        self.xq = QtWidgets.QPushButton(self.centralwidget)
        self.xq.setGeometry(QtCore.QRect(670, 170, 31, 31))
        self.xq.setObjectName("xq")
        self.q = QtWidgets.QPushButton(self.centralwidget)
        self.q.setGeometry(QtCore.QRect(670, 50, 31, 31))
        self.q.setObjectName("q")
        self.gq = QtWidgets.QPushButton(self.centralwidget)
        self.gq.setGeometry(QtCore.QRect(700, 50, 31, 31))
        self.gq.setObjectName("gq")
        self.rq = QtWidgets.QPushButton(self.centralwidget)
        self.rq.setGeometry(QtCore.QRect(700, 110, 31, 31))
        self.rq.setObjectName("rq")
        self.h = QtWidgets.QPushButton(self.centralwidget)
        self.h.setGeometry(QtCore.QRect(810, 170, 31, 31))
        self.h.setObjectName("h")
        self.hhh = QtWidgets.QPushButton(self.centralwidget)
        self.hhh.setGeometry(QtCore.QRect(840, 170, 31, 31))
        self.hhh.setObjectName("hhh")
        self.hh = QtWidgets.QPushButton(self.centralwidget)
        self.hh.setGeometry(QtCore.QRect(740, 170, 31, 31))
        self.hh.setObjectName("hh")
        self.ha = QtWidgets.QPushButton(self.centralwidget)
        self.ha.setGeometry(QtCore.QRect(770, 170, 31, 31))
        self.ha.setObjectName("ha")
        self.xa = QtWidgets.QPushButton(self.centralwidget)
        self.xa.setGeometry(QtCore.QRect(810, 50, 31, 31))
        self.xa.setObjectName("xa")
        self.rh = QtWidgets.QPushButton(self.centralwidget)
        self.rh.setGeometry(QtCore.QRect(350, 230, 31, 31))
        self.rh.setObjectName("rh")
        self.n = QtWidgets.QPushButton(self.centralwidget)
        self.n.setGeometry(QtCore.QRect(350, 80, 31, 31))
        self.n.setObjectName("n")
        self.zh = QtWidgets.QPushButton(self.centralwidget)
        self.zh.setGeometry(QtCore.QRect(350, 170, 31, 31))
        self.zh.setObjectName("zh")
        self.r = QtWidgets.QPushButton(self.centralwidget)
        self.r.setGeometry(QtCore.QRect(350, 110, 31, 31))
        self.r.setObjectName("r")
        self.l = QtWidgets.QPushButton(self.centralwidget)
        self.l.setGeometry(QtCore.QRect(350, 260, 31, 31))
        self.l.setObjectName("l")
        self.d = QtWidgets.QPushButton(self.centralwidget)
        self.d.setGeometry(QtCore.QRect(350, 50, 31, 31))
        self.d.setObjectName("d")
        self.rr = QtWidgets.QPushButton(self.centralwidget)
        self.rr.setGeometry(QtCore.QRect(350, 140, 31, 31))
        self.rr.setObjectName("rr")
        self.lzh = QtWidgets.QPushButton(self.centralwidget)
        self.lzh.setGeometry(QtCore.QRect(350, 200, 31, 31))
        self.lzh.setObjectName("lzh")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 191, 19))
        self.label_3.setObjectName("label_3")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 300, 221, 19))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(40, 330, 68, 19))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(150, 330, 131, 19))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(290, 330, 61, 19))
        self.label_24.setObjectName("label_24")
        self.ac = QtWidgets.QPushButton(self.centralwidget)
        self.ac.setGeometry(QtCore.QRect(20, 420, 31, 31))
        self.ac.setObjectName("ac")
        self.dc = QtWidgets.QPushButton(self.centralwidget)
        self.dc.setGeometry(QtCore.QRect(20, 390, 31, 31))
        self.dc.setObjectName("dc")
        self.bc = QtWidgets.QPushButton(self.centralwidget)
        self.bc.setGeometry(QtCore.QRect(20, 360, 31, 31))
        self.bc.setObjectName("bc")
        self.alc = QtWidgets.QPushButton(self.centralwidget)
        self.alc.setGeometry(QtCore.QRect(20, 480, 31, 31))
        self.alc.setObjectName("alc")
        self.pac = QtWidgets.QPushButton(self.centralwidget)
        self.pac.setGeometry(QtCore.QRect(20, 450, 31, 31))
        self.pac.setObjectName("pac")
        self.gqi = QtWidgets.QPushButton(self.centralwidget)
        self.gqi.setGeometry(QtCore.QRect(160, 480, 31, 31))
        self.gqi.setObjectName("gqi")
        self.gi = QtWidgets.QPushButton(self.centralwidget)
        self.gi.setGeometry(QtCore.QRect(160, 450, 31, 31))
        self.gi.setObjectName("gi")
        self.ji = QtWidgets.QPushButton(self.centralwidget)
        self.ji.setGeometry(QtCore.QRect(160, 420, 31, 31))
        self.ji.setObjectName("ji")
        self.bi = QtWidgets.QPushButton(self.centralwidget)
        self.bi.setGeometry(QtCore.QRect(160, 360, 31, 31))
        self.bi.setObjectName("bi")
        self.di = QtWidgets.QPushButton(self.centralwidget)
        self.di.setGeometry(QtCore.QRect(160, 390, 31, 31))
        self.di.setObjectName("di")
        self.pe = QtWidgets.QPushButton(self.centralwidget)
        self.pe.setGeometry(QtCore.QRect(280, 390, 31, 31))
        self.pe.setObjectName("pe")
        self.te = QtWidgets.QPushButton(self.centralwidget)
        self.te.setGeometry(QtCore.QRect(280, 420, 31, 31))
        self.te.setObjectName("te")
        self.ke = QtWidgets.QPushButton(self.centralwidget)
        self.ke.setGeometry(QtCore.QRect(280, 450, 31, 31))
        self.ke.setObjectName("ke")
        self.se = QtWidgets.QPushButton(self.centralwidget)
        self.se.setGeometry(QtCore.QRect(280, 480, 31, 31))
        self.se.setObjectName("se")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(60, 490, 91, 19))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(60, 430, 91, 19))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(60, 370, 68, 19))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(60, 460, 91, 19))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(60, 400, 68, 19))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(200, 400, 68, 19))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(200, 490, 91, 19))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(200, 430, 91, 19))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(200, 460, 91, 19))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(200, 370, 68, 19))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(320, 430, 121, 19))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(320, 460, 91, 19))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(320, 400, 68, 19))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(320, 490, 131, 19))
        self.label_39.setObjectName("label_39")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(20, 530, 221, 19))
        self.label_35.setObjectName("label_35")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(60, 600, 231, 19))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(350, 570, 201, 19))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(60, 630, 251, 19))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(60, 660, 221, 19))
        self.label_43.setObjectName("label_43")
        self.wy = QtWidgets.QPushButton(self.centralwidget)
        self.wy.setGeometry(QtCore.QRect(20, 620, 31, 31))
        self.wy.setObjectName("wy")
        self.wh = QtWidgets.QPushButton(self.centralwidget)
        self.wh.setGeometry(QtCore.QRect(20, 560, 31, 31))
        self.wh.setObjectName("wh")
        self.heg = QtWidgets.QPushButton(self.centralwidget)
        self.heg.setGeometry(QtCore.QRect(20, 650, 31, 31))
        self.heg.setObjectName("heg")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(60, 570, 221, 19))
        self.label_44.setObjectName("label_44")
        self.w = QtWidgets.QPushButton(self.centralwidget)
        self.w.setGeometry(QtCore.QRect(20, 590, 31, 31))
        self.w.setObjectName("w")
        self.aeg = QtWidgets.QPushButton(self.centralwidget)
        self.aeg.setGeometry(QtCore.QRect(310, 560, 31, 31))
        self.aeg.setObjectName("aeg")
        self.xeg = QtWidgets.QPushButton(self.centralwidget)
        self.xeg.setGeometry(QtCore.QRect(310, 590, 31, 31))
        self.xeg.setObjectName("xeg")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(350, 600, 201, 19))
        self.label_45.setObjectName("label_45")
        self.zy = QtWidgets.QPushButton(self.centralwidget)
        self.zy.setGeometry(QtCore.QRect(20, 710, 31, 31))
        self.zy.setObjectName("zy")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(60, 690, 241, 19))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(60, 720, 231, 19))
        self.label_49.setObjectName("label_49")
        self.sy = QtWidgets.QPushButton(self.centralwidget)
        self.sy.setGeometry(QtCore.QRect(20, 680, 31, 31))
        self.sy.setObjectName("sy")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(570, 300, 68, 19))
        self.label_50.setObjectName("label_50")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(800, 300, 61, 19))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(680, 300, 131, 19))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(480, 300, 68, 19))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(480, 340, 68, 19))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(480, 400, 121, 19))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(480, 520, 61, 19))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(480, 460, 91, 19))
        self.label_58.setObjectName("label_58")
        self.i = QtWidgets.QPushButton(self.centralwidget)
        self.i.setGeometry(QtCore.QRect(550, 330, 31, 31))
        self.i.setObjectName("i")
        self.y = QtWidgets.QPushButton(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(590, 330, 31, 31))
        self.y.setObjectName("y")
        self.il = QtWidgets.QPushButton(self.centralwidget)
        self.il.setGeometry(QtCore.QRect(600, 360, 31, 31))
        self.il.setObjectName("il")
        self.yl = QtWidgets.QPushButton(self.centralwidget)
        self.yl.setGeometry(QtCore.QRect(640, 360, 31, 31))
        self.yl.setObjectName("yl")
        self.oe = QtWidgets.QPushButton(self.centralwidget)
        self.oe.setGeometry(QtCore.QRect(610, 390, 31, 31))
        self.oe.setObjectName("oe")
        self.e = QtWidgets.QPushButton(self.centralwidget)
        self.e.setGeometry(QtCore.QRect(570, 390, 31, 31))
        self.e.setObjectName("e")
        self.et = QtWidgets.QPushButton(self.centralwidget)
        self.et.setGeometry(QtCore.QRect(590, 450, 31, 31))
        self.et.setObjectName("et")
        self.oet = QtWidgets.QPushButton(self.centralwidget)
        self.oet.setGeometry(QtCore.QRect(630, 450, 31, 31))
        self.oet.setObjectName("oet")
        self.oett = QtWidgets.QPushButton(self.centralwidget)
        self.oett.setGeometry(QtCore.QRect(650, 510, 31, 31))
        self.oett.setObjectName("oett")
        self.a = QtWidgets.QPushButton(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(610, 510, 31, 31))
        self.a.setObjectName("a")
        self.ae = QtWidgets.QPushButton(self.centralwidget)
        self.ae.setGeometry(QtCore.QRect(600, 480, 31, 31))
        self.ae.setObjectName("ae")
        self.ih = QtWidgets.QPushButton(self.centralwidget)
        self.ih.setGeometry(QtCore.QRect(670, 330, 31, 31))
        self.ih.setObjectName("ih")
        self.uh = QtWidgets.QPushButton(self.centralwidget)
        self.uh.setGeometry(QtCore.QRect(710, 330, 31, 31))
        self.uh.setObjectName("uh")
        self.eh = QtWidgets.QPushButton(self.centralwidget)
        self.eh.setGeometry(QtCore.QRect(680, 390, 31, 31))
        self.eh.setObjectName("eh")
        self.oh = QtWidgets.QPushButton(self.centralwidget)
        self.oh.setGeometry(QtCore.QRect(720, 390, 31, 31))
        self.oh.setObjectName("oh")
        self.a_ = QtWidgets.QPushButton(self.centralwidget)
        self.a_.setGeometry(QtCore.QRect(700, 420, 31, 31))
        self.a_.setObjectName("a_")
        self.eht = QtWidgets.QPushButton(self.centralwidget)
        self.eht.setGeometry(QtCore.QRect(690, 450, 31, 31))
        self.eht.setObjectName("eht")
        self.aw = QtWidgets.QPushButton(self.centralwidget)
        self.aw.setGeometry(QtCore.QRect(710, 480, 31, 31))
        self.aw.setObjectName("aw")
        self.oht = QtWidgets.QPushButton(self.centralwidget)
        self.oht.setGeometry(QtCore.QRect(730, 450, 31, 31))
        self.oht.setObjectName("oht")
        self.eu = QtWidgets.QPushButton(self.centralwidget)
        self.eu.setGeometry(QtCore.QRect(780, 330, 31, 31))
        self.eu.setObjectName("eu")
        self.u = QtWidgets.QPushButton(self.centralwidget)
        self.u.setGeometry(QtCore.QRect(820, 330, 31, 31))
        self.u.setObjectName("u")
        self.ul = QtWidgets.QPushButton(self.centralwidget)
        self.ul.setGeometry(QtCore.QRect(750, 360, 31, 31))
        self.ul.setObjectName("ul")
        self.ue = QtWidgets.QPushButton(self.centralwidget)
        self.ue.setGeometry(QtCore.QRect(780, 390, 31, 31))
        self.ue.setObjectName("ue")
        self.o = QtWidgets.QPushButton(self.centralwidget)
        self.o.setGeometry(QtCore.QRect(820, 390, 31, 31))
        self.o.setObjectName("o")
        self.aht = QtWidgets.QPushButton(self.centralwidget)
        self.aht.setGeometry(QtCore.QRect(780, 450, 31, 31))
        self.aht.setObjectName("aht")
        self.pushButton_110 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_110.setGeometry(QtCore.QRect(820, 450, 31, 31))
        self.pushButton_110.setObjectName("pushButton_110")
        self.ah = QtWidgets.QPushButton(self.centralwidget)
        self.ah.setGeometry(QtCore.QRect(780, 510, 31, 31))
        self.ah.setObjectName("ah")
        self.ao = QtWidgets.QPushButton(self.centralwidget)
        self.ao.setGeometry(QtCore.QRect(820, 510, 31, 31))
        self.ao.setObjectName("ao")
        self.pron_mode = QtWidgets.QRadioButton(self.centralwidget)
        self.pron_mode.setGeometry(QtCore.QRect(640, 590, 251, 23))
        self.pron_mode.setObjectName("pron_mode")
        self.t2s_mode = QtWidgets.QRadioButton(self.centralwidget)
        self.t2s_mode.setGeometry(QtCore.QRect(670, 620, 251, 23))
        self.t2s_mode.setObjectName("t2s_mode")
        self.t2s_pronunce = QtWidgets.QPushButton(self.centralwidget)
        self.t2s_pronunce.setGeometry(QtCore.QRect(390, 710, 112, 34))
        self.t2s_pronunce.setObjectName("t2s_pronunce")
        self.t2s_input = QtWidgets.QLineEdit(self.centralwidget)
        self.t2s_input.setGeometry(QtCore.QRect(390, 680, 461, 25))
        self.t2s_input.setObjectName("t2s_input")
        self.addfav = QtWidgets.QPushButton(self.centralwidget)
        self.addfav.setGeometry(QtCore.QRect(740, 710, 112, 34))
        self.addfav.setObjectName("addfav")
        self.fav_mode = QtWidgets.QRadioButton(self.centralwidget)
        self.fav_mode.setGeometry(QtCore.QRect(660, 650, 191, 23))
        self.fav_mode.setObjectName("fav_mode")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(190, 30, 91, 19))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(390, 30, 91, 19))
        self.label_60.setObjectName("label_60")
        self.savePron = QtWidgets.QPushButton(self.centralwidget)
        self.savePron.setGeometry(QtCore.QRect(510, 710, 161, 34))
        self.savePron.setObjectName("savePron")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(10, 30, 191, 19))
        self.label_46.setObjectName("label_46")
        ot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ot)
        self.statusbar.setObjectName("statusbar")
        ot.setStatusBar(self.statusbar)

        self.retranslateUi(ot)
        QtCore.QMetaObject.connectSlotsByName(ot)

    def retranslateUi(self, ot):
        _translate = QtCore.QCoreApplication.translate
        ot.setWindowTitle(_translate("ot", "IPA Laboratory"))
        self.label.setText(_translate("ot", "Bilabial"))
        self.label_2.setText(_translate("ot", "Labio-"))
        self.label_4.setText(_translate("ot", "Dental"))
        self.label_5.setText(_translate("ot", "Alveolar"))
        self.label_6.setText(_translate("ot", "Palatal"))
        self.label_7.setText(_translate("ot", "Post-"))
        self.label_8.setText(_translate("ot", "Retroflex"))
        self.label_9.setText(_translate("ot", "Velar"))
        self.label_10.setText(_translate("ot", "Uvular"))
        self.label_11.setText(_translate("ot", "Glottal"))
        self.label_12.setText(_translate("ot", "Pharyngeal"))
        self.label_13.setText(_translate("ot", "Plosive"))
        self.label_14.setText(_translate("ot", "Nasal"))
        self.label_15.setText(_translate("ot", "Tap"))
        self.label_16.setText(_translate("ot", "Trill"))
        self.label_17.setText(_translate("ot", "Fricative"))
        self.label_18.setText(_translate("ot", "Lat. Fricative"))
        self.label_19.setText(_translate("ot", "Approx."))
        self.label_20.setText(_translate("ot", "Lat. Approx."))
        self.p.setText(_translate("ot", "p"))
        self.b.setText(_translate("ot", "b"))
        self.m.setText(_translate("ot", "m"))
        self.br.setText(_translate("ot", "ʙ"))
        self.vh.setText(_translate("ot", "β"))
        self.fh.setText(_translate("ot", "ɸ"))
        self.mh.setText(_translate("ot", "ɱ"))
        self.vr.setText(_translate("ot", "ⱱ"))
        self.v.setText(_translate("ot", "v"))
        self.f.setText(_translate("ot", "f"))
        self.vi.setText(_translate("ot", "ʋ"))
        self.z_.setText(_translate("ot", "ʐ"))
        self.n_.setText(_translate("ot", "ɳ"))
        self.d_.setText(_translate("ot", "ɖ"))
        self.r_.setText(_translate("ot", "ɽ"))
        self.l_.setText(_translate("ot", "ɭ"))
        self.rh_.setText(_translate("ot", "ɻ"))
        self.s.setText(_translate("ot", "s"))
        self.lh.setText(_translate("ot", "ɬ"))
        self.dh.setText(_translate("ot", "ð"))
        self.th.setText(_translate("ot", "θ"))
        self.t.setText(_translate("ot", "t"))
        self.sh.setText(_translate("ot", "ʃ"))
        self.zh_2.setText(_translate("ot", "ʒ"))
        self.t_.setText(_translate("ot", "ʈ"))
        self.s_.setText(_translate("ot", "ʂ"))
        self.ny.setText(_translate("ot", "ɲ"))
        self.ghy.setText(_translate("ot", "ʝ"))
        self.c.setText(_translate("ot", "c"))
        self.j.setText(_translate("ot", "j"))
        self.xy.setText(_translate("ot", "ç"))
        self.ly.setText(_translate("ot", "ʎ"))
        self.jy.setText(_translate("ot", "ɟ"))
        self.g.setText(_translate("ot", "g"))
        self.k.setText(_translate("ot", "k"))
        self.ng.setText(_translate("ot", "ŋ"))
        self.x.setText(_translate("ot", "x"))
        self.gh.setText(_translate("ot", "ɣ"))
        self.lg.setText(_translate("ot", "ʟ"))
        self.jg.setText(_translate("ot", "ɰ"))
        self.ghq.setText(_translate("ot", "ʁ"))
        self.nq.setText(_translate("ot", "ɴ"))
        self.xq.setText(_translate("ot", "χ"))
        self.q.setText(_translate("ot", "q"))
        self.gq.setText(_translate("ot", "ɢ"))
        self.rq.setText(_translate("ot", "ʀ"))
        self.h.setText(_translate("ot", "h"))
        self.hhh.setText(_translate("ot", "ɦ"))
        self.hh.setText(_translate("ot", "ħ"))
        self.ha.setText(_translate("ot", "ʕ"))
        self.xa.setText(_translate("ot", "ʔ"))
        self.rh.setText(_translate("ot", "ɹ"))
        self.n.setText(_translate("ot", "n"))
        self.zh.setText(_translate("ot", "z"))
        self.r.setText(_translate("ot", "r"))
        self.l.setText(_translate("ot", "l"))
        self.d.setText(_translate("ot", "d"))
        self.rr.setText(_translate("ot", "ɾ"))
        self.lzh.setText(_translate("ot", "ɮ"))
        self.label_3.setText(_translate("ot", "Consonants"))
        self.label_21.setText(_translate("ot", "Consonants (Non-pulmonic)"))
        self.label_22.setText(_translate("ot", "Clicks"))
        self.label_23.setText(_translate("ot", "Voiced Implosives"))
        self.label_24.setText(_translate("ot", "Ejectives"))
        self.ac.setText(_translate("ot", "!"))
        self.dc.setText(_translate("ot", "ǀ"))
        self.bc.setText(_translate("ot", "ʘ"))
        self.alc.setText(_translate("ot", "ǁ"))
        self.pac.setText(_translate("ot", "ǂ"))
        self.gqi.setText(_translate("ot", "ʛ"))
        self.gi.setText(_translate("ot", "ɠ"))
        self.ji.setText(_translate("ot", "ʄ"))
        self.bi.setText(_translate("ot", "ɓ"))
        self.di.setText(_translate("ot", "ɗ"))
        self.pe.setText(_translate("ot", "p\'"))
        self.te.setText(_translate("ot", "t\'"))
        self.ke.setText(_translate("ot", "k\'"))
        self.se.setText(_translate("ot", "s\'"))
        self.label_25.setText(_translate("ot", "Alv.Lateral"))
        self.label_26.setText(_translate("ot", "Alveolar"))
        self.label_27.setText(_translate("ot", "Bilabial"))
        self.label_28.setText(_translate("ot", "Postalveolar"))
        self.label_29.setText(_translate("ot", "Dental"))
        self.label_30.setText(_translate("ot", "Alveolar"))
        self.label_31.setText(_translate("ot", "Uvular"))
        self.label_32.setText(_translate("ot", "Palatal"))
        self.label_33.setText(_translate("ot", "Velar"))
        self.label_34.setText(_translate("ot", "Bilabial"))
        self.label_36.setText(_translate("ot", "Dental/Alveolar"))
        self.label_37.setText(_translate("ot", "Velar"))
        self.label_38.setText(_translate("ot", "Bilabial"))
        self.label_39.setText(_translate("ot", "Alveolar Fricative"))
        self.label_35.setText(_translate("ot", "Other Consonants"))
        self.label_40.setText(_translate("ot", "Voiced labial-velar approximant"))
        self.label_41.setText(_translate("ot", "Voiced epiglottal fricative"))
        self.label_42.setText(_translate("ot", "Voiced labial-palatal approximant"))
        self.label_43.setText(_translate("ot", "Voiceless epiglottal fricative"))
        self.wy.setText(_translate("ot", "ɥ"))
        self.wh.setText(_translate("ot", "ʍ"))
        self.heg.setText(_translate("ot", "ʜ"))
        self.label_44.setText(_translate("ot", "Voiceless labial-velar fricative"))
        self.w.setText(_translate("ot", "w"))
        self.aeg.setText(_translate("ot", "ʢ"))
        self.xeg.setText(_translate("ot", "ʡ"))
        self.label_45.setText(_translate("ot", "Epiglottal plosive"))
        self.zy.setText(_translate("ot", "ʑ"))
        self.label_48.setText(_translate("ot", "Voiceless alveolo-palatal fricative"))
        self.label_49.setText(_translate("ot", "Voiced alveolo-palatal fricative"))
        self.sy.setText(_translate("ot", "ɕ"))
        self.label_50.setText(_translate("ot", "Front"))
        self.label_52.setText(_translate("ot", "Back"))
        self.label_53.setText(_translate("ot", "Central"))
        self.label_54.setText(_translate("ot", "Vowels"))
        self.label_55.setText(_translate("ot", "Close"))
        self.label_56.setText(_translate("ot", "Close-mid"))
        self.label_57.setText(_translate("ot", "Open"))
        self.label_58.setText(_translate("ot", "Open-mid"))
        self.i.setText(_translate("ot", "i"))
        self.y.setText(_translate("ot", "y"))
        self.il.setText(_translate("ot", "ɪ"))
        self.yl.setText(_translate("ot", "ʏ"))
        self.oe.setText(_translate("ot", "ø"))
        self.e.setText(_translate("ot", "e"))
        self.et.setText(_translate("ot", "ɛ"))
        self.oet.setText(_translate("ot", "œ"))
        self.oett.setText(_translate("ot", "ɶ"))
        self.a.setText(_translate("ot", "a"))
        self.ae.setText(_translate("ot", "æ"))
        self.ih.setText(_translate("ot", "ɨ"))
        self.uh.setText(_translate("ot", "ʉ"))
        self.eh.setText(_translate("ot", "ɘ"))
        self.oh.setText(_translate("ot", "ɵ"))
        self.a_.setText(_translate("ot", "ə"))
        self.eht.setText(_translate("ot", "ɜ"))
        self.aw.setText(_translate("ot", "ɐ"))
        self.oht.setText(_translate("ot", "ɞ"))
        self.eu.setText(_translate("ot", "ɯ"))
        self.u.setText(_translate("ot", "u"))
        self.ul.setText(_translate("ot", "ʊ"))
        self.ue.setText(_translate("ot", "ɤ"))
        self.o.setText(_translate("ot", "o"))
        self.aht.setText(_translate("ot", "ʌ"))
        self.pushButton_110.setText(_translate("ot", "ɔ"))
        self.ah.setText(_translate("ot", "ɑ"))
        self.ao.setText(_translate("ot", "ɒ"))
        self.pron_mode.setText(_translate("ot", "Pronunce alphabet mode"))
        self.t2s_mode.setText(_translate("ot", "Text-to-speech mode"))
        self.t2s_pronunce.setText(_translate("ot", "Pronunce"))
        self.addfav.setText(_translate("ot", "Add"))
        self.fav_mode.setText(_translate("ot", "Add to Favorite mode"))
        self.label_59.setText(_translate("ot", "dental"))
        self.label_60.setText(_translate("ot", "alveolar"))
        self.savePron.setText(_translate("ot", "Save pronunciation"))
        self.label_46.setText(_translate("ot", "(Pulmonic)"))

